server:
  port: 9000

spring:
  servlet:
    multipart:
      enabled: false



file:
  upload-path: /Users/weidian/Downloads
  download-path: /Users/weidian/Downloads
  download-file: /Users/weidian/weidian/media/lin/Server/ZLMediaKit/onvif/11/2023-09-14/182513-183515.mp4